galaxy_info:
  author: Karan Singh
  description: Ansible role to install and configure COSBench ( Cloud Object Storage Benchmarking Tool )
  company: Red Hat
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
  - system
  - storage
dependencies: []
